// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYPfwBZo5yhZas93odqA80Qn7OrR0KiVI',
    appId: '1:1020222733781:web:e857ecbfdeacbb68a3915c',
    messagingSenderId: '1020222733781',
    projectId: 'partsnapp',
    authDomain: 'partsnapp.firebaseapp.com',
    storageBucket: 'partsnapp.firebasestorage.app',
    measurementId: 'G-KS223920VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpGWP7LGj9NDsQnJvoGmaYSvc31uX8RZs',
    appId: '1:1020222733781:android:7b1eda4ff9f8661ca3915c',
    messagingSenderId: '1020222733781',
    projectId: 'partsnapp',
    storageBucket: 'partsnapp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYPfwBZo5yhZas93odqA80Qn7OrR0KiVI',
    appId: '1:1020222733781:web:ae2b3806a8f2a273a3915c',
    messagingSenderId: '1020222733781',
    projectId: 'partsnapp',
    authDomain: 'partsnapp.firebaseapp.com',
    storageBucket: 'partsnapp.firebasestorage.app',
    measurementId: 'G-WD5JJMWCBQ',
  );
}
